
---
- name: Start EC2 instances
  hosts: localhost
  connection: local
  become: yes

  vars_files:
    - pass.yml

  tasks:
    - name: Start EC2 instances with public IPs
      amazon.aws.ec2_instance:
        name: "new_ansible-instance"
        instance_type: t2.micro
        security_group: default
        region: ap-south-1
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        network:
          assign_public_ip: true
        image_id: "{{ item.image }}"
        tags:
          Environment: "{{ item.name }}"
      loop:
        - {{image: "ami-0f918f7e67a3323f0", name: "node-1"}}
        - {{image: "ami-0f918f7e67a3323f0", name: "node-2"}}
        - {{image: "ami-0144277607031eca2", name: "node-3"}}
